import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';
import React from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <div>
            <nav>
              <Link></Link>
            </nav>
          </div>
        </header>

        {children}
        <footer>&copy; Louis Perkins</footer>
      </body>
    </html>
  );
};

export default RootLayout;
